Add hacks for release.py to funx. It's a bit gross to have these in a simple trampoline tool, but practically speaking it's the best/most useful place.

diff --git a/bin/funx b/bin/funx
--- a/bin/funx
+++ b/bin/funx
@@ -65,7 +65,46 @@ function best_match()
 	fi
 
 	echo "$existing"
-	return
+}
+
+function release_dot_py_hacks()
+{
+	local cmd="$1"
+	local sdk="$SDKDIR"
+	local mkimage_src=
+	local mkimage_dst="$sdk/bin/Linux/x86_64/mkimage"
+
+	if [ $(uname) != "Darwin" ]; then
+		return
+	fi
+
+	cmd="$(basename "$cmd")"
+	if [ "$cmd" != "release.py" ]; then
+		return
+	fi
+
+	CLI.status "doing release.py hacks for Darwin..."
+
+	CLI.command "$sdk/scripts/bob" --sdkup -H Linux nvdimm_firmware
+	CLI.die_check $? "install nvdimm_firmware"
+
+	CLI.command brew install u-boot-tools
+	CLI.die_check $? "install mkimage"
+
+	mkimage_src=$(which mkimage)
+	CLI.die_ifz "$mkimage_src" "failed to find mkimage"
+
+	# We copy mkimage into the SDK rather than symlinking it because the release
+	# script will copy mkimage into the bundle, and Homebrew's permissions on
+	# stuff is generally non-writeable, so that would fail.
+	CLI.command mkdir -p "$sdk/bin/Linux/x86_64"
+	CLI.command rm "$mkimage_dst"
+
+	CLI.command cp "$mkimage_src" "$mkimage_dst"
+	CLI.die_check $? "copy mkimage"
+
+	CLI.command chmod u+w "$mkimage_dst"
+	CLI.die_check $? "chmod mkimage"
 }
 
 # MARK: Command Implementation
@@ -132,6 +171,7 @@ function __cmd()
 			cd "$O_WORKING_DIRECTORY"
 		fi
 
+		release_dot_py_hacks "$cmd"
 		PYTHONWARNINGS=ignore CLI.command "$cmd" "$@"
 	fi
 }
